# Generated by Django 4.1 on 2023-05-29 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_user_options_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('textauthor', models.CharField(default=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Имя юзера'), max_length=255, verbose_name='Автор статьи')),
                ('date_post', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата')),
                ('type', models.IntegerField(choices=[(1, 'СРОЧНАЯ НОВОСТЬ'), (2, 'НОВОСТЬ ДНЯ'), (3, 'ОБЫЧНАЯ')], default=3, verbose_name='Тип новости')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Имя юзера')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
