# Generated by Django 4.1 on 2023-06-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_textauthor_post_text_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='templates/img/service-6.jpg', upload_to='', verbose_name='Изображение'),
        ),
    ]
