# Generated by Django 4.1 on 2023-06-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='service-6.jpg', upload_to='', verbose_name='Изображение'),
        ),
    ]
